[tool.pylint.master]
output-format = "colorized"


[tool.pylint.messages_control]
disable = [
    "line-too-long",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "invalid-name",
    "import-error",
    "relative-beyond-top-level",
    "too-many-instance-attributes",
    "multiple-statements",
    "arguments-differ",
    "arguments-renamed",
    "too-few-public-methods",
    "consider-iterating-dictionary",
    "wrong-import-order",
    "no-else-return",
    "unnecessary-lambda",
    "consider-using-dict-items",
    "too-many-locals",
    "too-many-arguments"
]