# name: GCloud Function Release
# 
# on:
#     push:
#         branches: [master]
# 
# jobs:
# 
#     release:
# 
#         name: Release [${{ matrix.function }}]
#         runs-on: ubuntu-latest
#         strategy:
#             matrix:
#                 include:
#                   - function: get_runner
#                   - function: get_runner_remote
# 
#         steps:
# 
#           - id: checkout
#             name: Checkout
#             uses: actions/checkout@v3
# 
#           - id: unpack
#             name: Unpack
#             run: mv api/* .
# 
#           - id: auth
#             name: GCloud Auth
#             uses: google-github-actions/auth@v0
#             with:
#                 credentials_json: '${{ secrets.GCLOUD_MASTER_SA_KEY }}'
# 
#           - id: deploy
#             name: Deploy [${{ matrix.function }}]
#             uses: google-github-actions/deploy-cloud-functions@v0
#             with: 
#                 name: ${{ matrix.function }}
#                 runtime: python37
#                 memory_mb: 256MB
#                 region: australia-southeast1
#                 project_id: park-run