name: Refresh Events

on:
    schedule:
      - cron: "0 0 * * 2"

jobs:
    refresh:
        name: Refresh Events
        runs-on: ubuntu-latest
        steps:
            
          - uses: actions/checkout@v3
        
          - name: Install Python
            uses: actions/setup-python@v4
            with:
                python-version: 3.10
        
          - name: Install Requirements
            run: pip install --upgrade -f requirements.txt
            
          - name: Refresh Events
            run: python3 refresh.py
