name: Refresh Events

on:
    schedule:
      - cron: "0 0 * * 2"
    
    push:
        branches: [master]
    
    workflow_dispatch:

jobs:
    refresh:
        name: Refresh Events
        runs-on: ubuntu-latest
        steps:
        
          - name: Cronitor Start
            run: curl https://cronitor.link/p/${{ secrets.CRONITOR_KEY }}/s85I7g?state=run
            
          - uses: actions/checkout@v3
        
          - name: Install Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"
        
          - name: Debug
            run: ls
        
          - name: Install Requirements
            run: pip install --upgrade -r requirements.txt
            
          - name: Refresh Events
            run: python3 refresh.py
            env:
                GCLOUD_MASTER_SA_KEY: '${{ secrets.GCLOUD_MASTER_SA_KEY }}'
                GCLOUD_MAPS_KEY: '${{ secrets.GCLOUD_MAPS_KEY }}'
                
          - name: Cronitor Success
            if: success()
            run: curl https://cronitor.link/p/${{ secrets.CRONITOR_KEY }}/s85I7g?state=complete
            
          - name: Cronitor Failure
            if: failure()
            run: curl https://cronitor.link/p/${{ secrets.CRONITOR_KEY }}/s85I7g?state=fail
